<?php

namespace Database\Seeders;

use App\Models\FanZone;
use Illuminate\Database\Seeder;

class FanZoneSeeder extends Seeder
{
    public function run(): void
    {
        $fanZones = [
            // Europe · Afrique
            [
                'city_name' => 'Rabat',
                'country' => 'Maroc',
                'country_code' => 'ma',
                'stadium_name' => 'Grand Stade Hassan II',
                'capacity' => '115 000',
                'matches_count' => 9,
                'zone_name' => 'Zone Diplomatique',
                'description' => 'Le plus grand stade du monde. Rabat s\'impose comme la vitrine africaine et maghrébine de ce tournoi historique.',
                'image_url' => 'https://images.unsplash.com/photo-1565967511849-76a60a516170?w=900&q=80&fit=crop',
                'opening_hours' => '10h – 00h',
                'is_centenary' => false,
                'group_label' => 'Europe · Afrique',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'city_name' => 'Madrid',
                'country' => 'Espagne',
                'country_code' => 'es',
                'stadium_name' => 'Santiago Bernabéu',
                'capacity' => '81 044',
                'matches_count' => 8,
                'zone_name' => 'Plaza de Colón',
                'description' => 'La capitale ibérique et son mythique Bernabéu accueillent les plus grands chocs et demi-finales du tournoi.',
                'image_url' => 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=900&q=80&fit=crop',
                'opening_hours' => '10h – 00h',
                'is_centenary' => false,
                'group_label' => 'Europe · Afrique',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'city_name' => 'Barcelone',
                'country' => 'Espagne',
                'country_code' => 'es',
                'stadium_name' => 'Spotify Camp Nou',
                'capacity' => '99 354',
                'matches_count' => 7,
                'zone_name' => 'Passeig de Gràcia',
                'description' => 'Le Camp Nou entièrement rénové devient l\'une des plus belles arènes de la compétition. Architecture et foot unis.',
                'image_url' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&q=80&fit=crop',
                'opening_hours' => '10h – 00h',
                'is_centenary' => false,
                'group_label' => 'Europe · Afrique',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'city_name' => 'Lisbonne',
                'country' => 'Portugal',
                'country_code' => 'pt',
                'stadium_name' => 'Estádio da Luz',
                'capacity' => '65 647',
                'matches_count' => 7,
                'zone_name' => 'Parque das Nações',
                'description' => 'Au bord du Tage, Lisbonne mêle passion du Fado et ferveur footballistique dans une atmosphère unique.',
                'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80&fit=crop',
                'opening_hours' => '10h – 00h',
                'is_centenary' => false,
                'group_label' => 'Europe · Afrique',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'city_name' => 'Porto',
                'country' => 'Portugal',
                'country_code' => 'pt',
                'stadium_name' => 'Estádio do Dragão',
                'capacity' => '50 033',
                'matches_count' => 5,
                'zone_name' => 'Avenida dos Aliados',
                'description' => 'La cité du vin et du football passionné accueille cinq matchs de groupes dans l\'emblématique Estádio do Dragão.',
                'image_url' => 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=900&q=80&fit=crop',
                'opening_hours' => '10h – 00h',
                'is_centenary' => false,
                'group_label' => 'Europe · Afrique',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'city_name' => 'Séville',
                'country' => 'Espagne',
                'country_code' => 'es',
                'stadium_name' => 'Estadio La Cartuja',
                'capacity' => '60 000',
                'matches_count' => 6,
                'zone_name' => 'Alameda de Hércules',
                'description' => 'Séville, cœur flamenca de l\'Andalousie, apporte chaleur humaine et culture dans le plus beau des tournois.',
                'image_url' => 'https://images.unsplash.com/photo-1534442845756-8ad9e52fa8a1?w=900&q=80&fit=crop',
                'opening_hours' => '10h – 00h',
                'is_centenary' => false,
                'group_label' => 'Europe · Afrique',
                'sort_order' => 6,
                'is_active' => true,
            ],
            // Amérique du Sud · Centenaire
            [
                'city_name' => 'Buenos Aires',
                'country' => 'Argentine',
                'country_code' => 'ar',
                'stadium_name' => 'Estadio Monumental',
                'capacity' => '84 567',
                'matches_count' => 1,
                'zone_name' => 'Puerto Madero',
                'description' => 'Match centenaire FIFA 2030. Le temple du foot argentin ouvre ses portes pour un rendez-vous unique dans l\'histoire.',
                'image_url' => 'https://images.unsplash.com/photo-1612294037637-ec328d0e075e?w=900&q=80&fit=crop',
                'opening_hours' => '10h – 00h',
                'is_centenary' => true,
                'group_label' => 'Amérique du Sud · Centenaire',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'city_name' => 'Montevideo',
                'country' => 'Uruguay',
                'country_code' => 'uy',
                'stadium_name' => 'Estadio Centenario',
                'capacity' => '60 235',
                'matches_count' => 1,
                'zone_name' => 'Rambla de Montevideo',
                'description' => 'Là où tout a commencé. Le Centenario, berceau de la première Coupe du Monde 1930, célèbre 100 ans de football.',
                'image_url' => 'https://images.unsplash.com/photo-1586982530409-1e4ff7125a29?w=900&q=80&fit=crop',
                'opening_hours' => '10h – 00h',
                'is_centenary' => true,
                'group_label' => 'Amérique du Sud · Centenaire',
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'city_name' => 'Asunción',
                'country' => 'Paraguay',
                'country_code' => 'py',
                'stadium_name' => 'Estadio Defensores del Chaco',
                'capacity' => '42 354',
                'matches_count' => 1,
                'zone_name' => 'Costanera de Asunción',
                'description' => 'Troisième nation de la célébration centenaire, Asunción ferme ce triptyque historique sud-américain avec fierté.',
                'image_url' => 'https://images.unsplash.com/photo-1596568899404-b1e48c5d0f3a?w=900&q=80&fit=crop',
                'opening_hours' => '10h – 00h',
                'is_centenary' => true,
                'group_label' => 'Amérique du Sud · Centenaire',
                'sort_order' => 9,
                'is_active' => true,
            ],
        ];

        foreach ($fanZones as $fanZone) {
            FanZone::create($fanZone);
        }
    }
}