<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Team;

class TeamSeeder extends Seeder
{
    public function run(): void
    {
        Team::truncate();

        $teams = [
            // ── GROUPE A ──
            ['name'=>'USA',          'code'=>'USA','flag'=>'us','group_name'=>'Groupe A','coach'=>'Mauricio Pochettino','captain'=>'Christian Pulisic','world_ranking'=>11,'world_cup_titles'=>0,'key_player'=>'Christian Pulisic','description'=>'Co-organisateurs et favoris à domicile, les États-Unis veulent marquer l\'histoire avec une grande performance en 2026.','image_url'=>'https://images.unsplash.com/photo-1556056504-5c7696c4c28d?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Panama',       'code'=>'PAN','flag'=>'pa','group_name'=>'Groupe A','coach'=>'Thomas Christiansen','captain'=>'Roderick Miller','world_ranking'=>49,'world_cup_titles'=>0,'key_player'=>'Ismael Díaz','description'=>'Le Panama dispute sa deuxième Coupe du Monde et vise une qualification historique en phase finale.','image_url'=>'https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Albanie',      'code'=>'ALB','flag'=>'al','group_name'=>'Groupe A','coach'=>'Sylvinho','captain'=>'Berat Djimsiti','world_ranking'=>66,'world_cup_titles'=>0,'key_player'=>'Jasir Asani','description'=>'L\'Albanie fait ses débuts en Coupe du Monde et représente une belle surprise de ces qualifications.','image_url'=>'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Ukraine',      'code'=>'UKR','flag'=>'ua','group_name'=>'Groupe A','coach'=>'Serhiy Rebrov','captain'=>'Andriy Yarmolenko','world_ranking'=>22,'world_cup_titles'=>0,'key_player'=>'Mykhailo Mudryk','description'=>'L\'Ukraine, malgré un contexte difficile, a réussi à se qualifier et porte l\'espoir d\'une nation tout entière.','image_url'=>'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE B ──
            ['name'=>'Mexique',      'code'=>'MEX','flag'=>'mx','group_name'=>'Groupe B','coach'=>'Javier Aguirre','captain'=>'Héctor Herrera','world_ranking'=>16,'world_cup_titles'=>0,'key_player'=>'Hirving Lozano','description'=>'Co-organisateur et nation phare de la CONCACAF, le Mexique rêve enfin de dépasser les quarts de finale.','image_url'=>'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Équateur',     'code'=>'ECU','flag'=>'ec','group_name'=>'Groupe B','coach'=>'Sebastián Beccacece','captain'=>'Enner Valencia','world_ranking'=>34,'world_cup_titles'=>0,'key_player'=>'Kendry Páez','description'=>'L\'Équateur revient en force avec une génération talentueuse menée par le prodige Kendry Páez.','image_url'=>'https://images.unsplash.com/photo-1582239401768-3fa44026da73?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Jamaïque',     'code'=>'JAM','flag'=>'jm','group_name'=>'Groupe B','coach'=>'Steve McClaren','captain'=>'Bobby Reid','world_ranking'=>58,'world_cup_titles'=>0,'key_player'=>'Michail Antonio','description'=>'La Jamaïque effectue son grand retour en Coupe du Monde avec une équipe physique et enthousiasmante.','image_url'=>'https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Venezuela',    'code'=>'VEN','flag'=>'ve','group_name'=>'Groupe B','coach'=>'Fernando Batista','captain'=>'Tomás Rincón','world_ranking'=>30,'world_cup_titles'=>0,'key_player'=>'Yangel Herrera','description'=>'Pour la première fois de son histoire, le Venezuela se qualifie pour une Coupe du Monde — un moment historique.','image_url'=>'https://images.unsplash.com/photo-1543351611-58f69d7c1781?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE C ──
            ['name'=>'Canada',       'code'=>'CAN','flag'=>'ca','group_name'=>'Groupe C','coach'=>'Jesse Marsch','captain'=>'Atiba Hutchinson','world_ranking'=>40,'world_cup_titles'=>0,'key_player'=>'Alphonso Davies','description'=>'Co-organisateur, le Canada revient en Coupe du Monde après 40 ans avec une génération dorée menée par Alphonso Davies.','image_url'=>'https://images.unsplash.com/photo-1559564614-a399728b70ba?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Honduras',     'code'=>'HON','flag'=>'hn','group_name'=>'Groupe C','coach'=>'Reinaldo Rueda','captain'=>'Romell Quioto','world_ranking'=>80,'world_cup_titles'=>0,'key_player'=>'Romell Quioto','description'=>'Le Honduras espère créer la surprise en phase de groupes lors de ce retour en Coupe du Monde.','image_url'=>'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Maroc',        'code'=>'MAR','flag'=>'ma','group_name'=>'Groupe C','coach'=>'Walid Regragui','captain'=>'Romain Saïss','world_ranking'=>13,'world_cup_titles'=>0,'key_player'=>'Achraf Hakimi','description'=>'Les Lions de l\'Atlas, demi-finalistes historiques en 2022, reviennent avec une équipe soudée pour conquérir le monde.','image_url'=>'https://images.unsplash.com/photo-1597830219514-e601f029924d?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Belgique',     'code'=>'BEL','flag'=>'be','group_name'=>'Groupe C','coach'=>'Domenico Tedesco','captain'=>'Kevin De Bruyne','world_ranking'=>3,'world_cup_titles'=>0,'key_player'=>'Kevin De Bruyne','description'=>'Une nouvelle génération belge veut enfin transformer le potentiel en trophée mondial.','image_url'=>'https://images.unsplash.com/photo-1511886929837-329f79011999?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE D ──
            ['name'=>'Espagne',      'code'=>'ESP','flag'=>'es','group_name'=>'Groupe D','coach'=>'Luis de la Fuente','captain'=>'Álvaro Morata','world_ranking'=>8,'world_cup_titles'=>1,'key_player'=>'Lamine Yamal','description'=>'La Roja, championne d\'Europe 2024, mise sur sa nouvelle génération dorée pour décrocher une deuxième étoile.','image_url'=>'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Brésil',       'code'=>'BRA','flag'=>'br','group_name'=>'Groupe D','coach'=>'Dorival Júnior','captain'=>'Danilo','world_ranking'=>5,'world_cup_titles'=>5,'key_player'=>'Vinícius Júnior','description'=>'La Seleção, nation la plus titrée, cherche à mettre fin à une longue attente pour son sixième sacre mondial.','image_url'=>'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Japon',        'code'=>'JPN','flag'=>'jp','group_name'=>'Groupe D','coach'=>'Hajime Moriyasu','captain'=>'Wataru Endo','world_ranking'=>18,'world_cup_titles'=>0,'key_player'=>'Takefusa Kubo','description'=>'Les Samouraïs Bleus, connus pour leur discipline et vitesse, sont capables de renverser n\'importe quel géant.','image_url'=>'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Cameroun',     'code'=>'CMR','flag'=>'cm','group_name'=>'Groupe D','coach'=>'Marc Brys','captain'=>'Vincent Aboubakar','world_ranking'=>42,'world_cup_titles'=>0,'key_player'=>'André Onana','description'=>'Les Lions Indomptables du Cameroun reviennent avec la flamme de l\'Afrique dans le cœur.','image_url'=>'https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE E ──
            ['name'=>'France',       'code'=>'FRA','flag'=>'fr','group_name'=>'Groupe E','coach'=>'Didier Deschamps','captain'=>'Kylian Mbappé','world_ranking'=>2,'world_cup_titles'=>2,'key_player'=>'Kylian Mbappé','description'=>'Avec une profondeur de banc inégalée et des stars mondiales, les Bleus visent une troisième étoile.','image_url'=>'https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Argentine',    'code'=>'ARG','flag'=>'ar','group_name'=>'Groupe E','coach'=>'Lionel Scaloni','captain'=>'Lionel Messi','world_ranking'=>1,'world_cup_titles'=>3,'key_player'=>'Lionel Messi','description'=>'Les champions en titre sont de retour. L\'Albiceleste, menée par le légendaire Messi, reste la nation à battre.','image_url'=>'https://images.unsplash.com/photo-1589133465492-4d40026e2a2a?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Australie',    'code'=>'AUS','flag'=>'au','group_name'=>'Groupe E','coach'=>'Tony Popovic','captain'=>'Mat Ryan','world_ranking'=>24,'world_cup_titles'=>0,'key_player'=>'Mitchell Duke','description'=>'Les Socceroos continuent de progresser sur la scène mondiale avec une génération prometteuse.','image_url'=>'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Arabie Saoudite','code'=>'KSA','flag'=>'sa','group_name'=>'Groupe E','coach'=>'Herve Renard','captain'=>'Salem Al-Dawsari','world_ranking'=>56,'world_cup_titles'=>0,'key_player'=>'Salem Al-Dawsari','description'=>'L\'Arabie Saoudite, après le choc contre l\'Argentine en 2022, veut confirmer son statut de force émergente.','image_url'=>'https://images.unsplash.com/photo-1556056504-5c7696c4c28d?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE F ──
            ['name'=>'Allemagne',    'code'=>'GER','flag'=>'de','group_name'=>'Groupe F','coach'=>'Julian Nagelsmann','captain'=>'Joshua Kimmich','world_ranking'=>12,'world_cup_titles'=>4,'key_player'=>'Jamal Musiala','description'=>'La Mannschaft, en reconstruction réussie, veut retrouver son statut de géant mondial sur le terrain.','image_url'=>'https://images.unsplash.com/photo-1543351611-58f69d7c1781?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Portugal',     'code'=>'POR','flag'=>'pt','group_name'=>'Groupe F','coach'=>'Roberto Martínez','captain'=>'Cristiano Ronaldo','world_ranking'=>6,'world_cup_titles'=>0,'key_player'=>'Cristiano Ronaldo','description'=>'Une équipe mêlant expérience de légende et jeunes prodiges, prête à marquer l\'histoire mondiale.','image_url'=>'https://images.unsplash.com/photo-1582239401768-3fa44026da73?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Sénégal',      'code'=>'SEN','flag'=>'sn','group_name'=>'Groupe F','coach'=>'Aliou Cissé','captain'=>'Kalidou Koulibaly','world_ranking'=>20,'world_cup_titles'=>0,'key_player'=>'Sadio Mané','description'=>'La meilleure nation africaine de ces dernières années veut porter haut les couleurs du continent.','image_url'=>'https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Nouvelle-Zélande','code'=>'NZL','flag'=>'nz','group_name'=>'Groupe F','coach'=>'Darren Bazeley','captain'=>'Winston Reid','world_ranking'=>95,'world_cup_titles'=>0,'key_player'=>'Chris Wood','description'=>'Les All Whites de Nouvelle-Zélande espèrent créer la surprise lors de leur retour en Coupe du Monde.','image_url'=>'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE G ──
            ['name'=>'Angleterre',   'code'=>'ENG','flag'=>'gb','group_name'=>'Groupe G','coach'=>'Thomas Tuchel','captain'=>'Harry Kane','world_ranking'=>4,'world_cup_titles'=>1,'key_player'=>'Jude Bellingham','description'=>'Les Three Lions, finalistes européens, comptent sur leur armada offensive pour ramener le trophée à la maison.','image_url'=>'https://images.unsplash.com/photo-1511886929837-329f79011999?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Pays-Bas',     'code'=>'NED','flag'=>'nl','group_name'=>'Groupe G','coach'=>'Ronald Koeman','captain'=>'Virgil van Dijk','world_ranking'=>7,'world_cup_titles'=>0,'key_player'=>'Cody Gakpo','description'=>'La Hollande, avec ses stars européennes, ambitionne d\'atteindre enfin son premier titre mondial.','image_url'=>'https://images.unsplash.com/photo-1559564614-a399728b70ba?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Iran',         'code'=>'IRN','flag'=>'ir','group_name'=>'Groupe G','coach'=>'Amir Ghalenoei','captain'=>'Ehsan Hajsafi','world_ranking'=>22,'world_cup_titles'=>0,'key_player'=>'Mehdi Taremi','description'=>'L\'Iran, fort de sa solidité défensive, vise une qualification historique en phase à élimination directe.','image_url'=>'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Pérou',        'code'=>'PER','flag'=>'pe','group_name'=>'Groupe G','coach'=>'Jorge Fossati','captain'=>'Paolo Guerrero','world_ranking'=>37,'world_cup_titles'=>0,'key_player'=>'André Carrillo','description'=>'Le Pérou revient en Coupe du Monde avec la détermination de dépasser le premier tour.','image_url'=>'https://images.unsplash.com/photo-1582239401768-3fa44026da73?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE H ──
            ['name'=>'Uruguay',      'code'=>'URU','flag'=>'uy','group_name'=>'Groupe H','coach'=>'Marcelo Bielsa','captain'=>'José María Giménez','world_ranking'=>17,'world_cup_titles'=>2,'key_player'=>'Federico Valverde','description'=>'L\'Uruguay, nation pionnière du football mondial, ne manque jamais de caractère et d\'ambition.','image_url'=>'https://images.unsplash.com/photo-1543351611-58f69d7c1781?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Colombie',     'code'=>'COL','flag'=>'co','group_name'=>'Groupe H','coach'=>'Néstor Lorenzo','captain'=>'James Rodríguez','world_ranking'=>14,'world_cup_titles'=>0,'key_player'=>'James Rodríguez','description'=>'La Colombie arrive en grande forme et vise les derniers carrés avec James Rodríguez en maître.','image_url'=>'https://images.unsplash.com/photo-1589133465492-4d40026e2a2a?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Côte d\'Ivoire','code'=>'CIV','flag'=>'ci','group_name'=>'Groupe H','coach'=>'Emerse Faé','captain'=>'Sébastien Haller','world_ranking'=>31,'world_cup_titles'=>0,'key_player'=>'Sébastien Haller','description'=>'Les Éléphants de Côte d\'Ivoire visent une qualification en huitièmes en s\'appuyant sur leur expérience africaine.','image_url'=>'https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Paraguay',     'code'=>'PAR','flag'=>'py','group_name'=>'Groupe H','coach'=>'Gustavo Alfaro','captain'=>'Miguel Almirón','world_ranking'=>65,'world_cup_titles'=>0,'key_player'=>'Miguel Almirón','description'=>'Le Paraguay revient en Coupe du Monde avec la passion d\'une nation de football sud-américain.','image_url'=>'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE I ──
            ['name'=>'Croatie',      'code'=>'CRO','flag'=>'hr','group_name'=>'Groupe I','coach'=>'Zlatko Dalić','captain'=>'Luka Modrić','world_ranking'=>10,'world_cup_titles'=>0,'key_player'=>'Luka Modrić','description'=>'Les vice-champions du monde 2018 sont portés par le génie éternel de Luka Modrić.','image_url'=>'https://images.unsplash.com/photo-1559564614-a399728b70ba?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Danemark',     'code'=>'DEN','flag'=>'dk','group_name'=>'Groupe I','coach'=>'Kasper Hjulmand','captain'=>'Simon Kjær','world_ranking'=>21,'world_cup_titles'=>0,'key_player'=>'Christian Eriksen','description'=>'Le Danemark mise sur son organisation collective irréprochable pour atteindre les phases finales.','image_url'=>'https://images.unsplash.com/photo-1511886929837-329f79011999?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Qatar',        'code'=>'QAT','flag'=>'qa','group_name'=>'Groupe I','coach'=>'Marquez Lopez','captain'=>'Hassan Al-Haydos','world_ranking'=>38,'world_cup_titles'=>0,'key_player'=>'Akram Afif','description'=>'Les champions d\'Asie entendent aller plus loin que lors de leur première participation en 2022.','image_url'=>'https://images.unsplash.com/photo-1556056504-5c7696c4c28d?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Bolivie',      'code'=>'BOL','flag'=>'bo','group_name'=>'Groupe I','coach'=>'Óscar Villegas','captain'=>'Marcelo Martins','world_ranking'=>85,'world_cup_titles'=>0,'key_player'=>'Marcelo Martins','description'=>'La Bolivie marque son retour sur la scène mondiale après des décennies d\'absence.','image_url'=>'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE J ──
            ['name'=>'Italie',       'code'=>'ITA','flag'=>'it','group_name'=>'Groupe J','coach'=>'Luciano Spalletti','captain'=>'Gianluigi Donnarumma','world_ranking'=>9,'world_cup_titles'=>4,'key_player'=>'Federico Chiesa','description'=>'Après avoir manqué la précédente édition, la Squadra Azzurra revient avec une ferveur renouvelée.','image_url'=>'https://images.unsplash.com/photo-1559564614-a399728b70ba?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Corée du Sud', 'code'=>'KOR','flag'=>'kr','group_name'=>'Groupe J','coach'=>'Hong Myung-bo','captain'=>'Son Heung-min','world_ranking'=>23,'world_cup_titles'=>0,'key_player'=>'Son Heung-min','description'=>'Les Taeguk Warriors, portés par Son Heung-min, visent un nouveau quart de finale historique.','image_url'=>'https://images.unsplash.com/photo-1543351611-58f69d7c1781?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Algérie',      'code'=>'ALG','flag'=>'dz','group_name'=>'Groupe J','coach'=>'Vladimir Petkovic','captain'=>'Riyad Mahrez','world_ranking'=>36,'world_cup_titles'=>0,'key_player'=>'Riyad Mahrez','description'=>'Les Fennecs d\'Algérie, forts d\'une AFCON victorieuse, veulent briller sur la scène mondiale.','image_url'=>'https://images.unsplash.com/photo-1597830219514-e601f029924d?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Chili',        'code'=>'CHI','flag'=>'cl','group_name'=>'Groupe J','coach'=>'Ricardo Gareca','captain'=>'Alexis Sánchez','world_ranking'=>45,'world_cup_titles'=>0,'key_player'=>'Alexis Sánchez','description'=>'Le Chili revient en Coupe du Monde avec la mentalité guerrière de ses champions continentaux.','image_url'=>'https://images.unsplash.com/photo-1582239401768-3fa44026da73?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE K ──
            ['name'=>'Suisse',       'code'=>'SUI','flag'=>'ch','group_name'=>'Groupe K','coach'=>'Murat Yakin','captain'=>'Granit Xhaka','world_ranking'=>19,'world_cup_titles'=>0,'key_player'=>'Granit Xhaka','description'=>'La Suisse, toujours régulière et solide, vise enfin les demi-finales pour la première fois de son histoire.','image_url'=>'https://images.unsplash.com/photo-1511886929837-329f79011999?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Turquie',      'code'=>'TUR','flag'=>'tr','group_name'=>'Groupe K','coach'=>'Vincenzo Montella','captain'=>'Hakan Çalhanoğlu','world_ranking'=>29,'world_cup_titles'=>0,'key_player'=>'Hakan Çalhanoğlu','description'=>'La Turquie revient en Coupe du Monde avec ambition, portée par une génération de joueurs de premier plan.','image_url'=>'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Nigeria',      'code'=>'NGA','flag'=>'ng','group_name'=>'Groupe K','coach'=>'Finidi George','captain'=>'William Troost-Ekong','world_ranking'=>35,'world_cup_titles'=>0,'key_player'=>'Victor Osimhen','description'=>'Les Super Eagles du Nigeria misent sur le talent de Victor Osimhen pour briller à l\'échelle mondiale.','image_url'=>'https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Costa Rica',   'code'=>'CRC','flag'=>'cr','group_name'=>'Groupe K','coach'=>'Gustavo Alfaro','captain'=>'Bryan Ruiz','world_ranking'=>50,'world_cup_titles'=>0,'key_player'=>'Joel Campbell','description'=>'Le Costa Rica, surprise de 2014 avec son fameux quart de finale, vise une nouvelle sensation.','image_url'=>'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800'],

            // ── GROUPE L ──
            ['name'=>'Mexique 2',    'code'=>'TBD','flag'=>'mx','group_name'=>'Groupe L','coach'=>'À déterminer','captain'=>'À déterminer','world_ranking'=>0,'world_cup_titles'=>0,'key_player'=>'À déterminer','description'=>'Nation qualifiée — détails à confirmer selon le tirage au sort officiel FIFA.','image_url'=>'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Égypte',       'code'=>'EGY','flag'=>'eg','group_name'=>'Groupe L','coach'=>'Rui Vitória','captain'=>'Mohamed Salah','world_ranking'=>33,'world_cup_titles'=>0,'key_player'=>'Mohamed Salah','description'=>'Les Pharaons d\'Égypte sont emmenés par la superstar Mohamed Salah qui rêve de sa première Coupe du Monde.','image_url'=>'https://images.unsplash.com/photo-1597830219514-e601f029924d?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Serbie',       'code'=>'SRB','flag'=>'rs','group_name'=>'Groupe L','coach'=>'Dragan Stojković','captain'=>'Aleksandar Mitrović','world_ranking'=>28,'world_cup_titles'=>0,'key_player'=>'Dušan Vlahović','description'=>'La Serbie, forte de sa génération de talents, vise une qualification historique en huitièmes de finale.','image_url'=>'https://images.unsplash.com/photo-1543351611-58f69d7c1781?auto=format&fit=crop&q=80&w=800'],
            ['name'=>'Ghana',        'code'=>'GHA','flag'=>'gh','group_name'=>'Groupe L','coach'=>'Otto Addo','captain'=>'Thomas Partey','world_ranking'=>60,'world_cup_titles'=>0,'key_player'=>'Mohammed Kudus','description'=>'Les Black Stars du Ghana reviennent avec la flamme de 2010 et l\'ambition de dépasser les quarts de finale.','image_url'=>'https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&q=80&w=800'],
        ];

        foreach ($teams as $t) {
            Team::create($t);
        }
    }
}
